// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChildA: typeof import('./src/components/ChildA.vue')['default']
    ChildB: typeof import('./src/components/ChildB.vue')['default']
    ChildC: typeof import('./src/components/ChildC.vue')['default']
    ChildD: typeof import('./src/components/ChildD.vue')['default']
    ChildE: typeof import('./src/components/ChildE.vue')['default']
    ChildF: typeof import('./src/components/ChildF.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
  }
}
